
package com.grepcepws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.grepcepws.entity.xsd.ObterCepResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GrepCepPortType", targetNamespace = "http://ws.grepcepws.com")
@XmlSeeAlso({
    com.grepcepws.entity.xsd.ObjectFactory.class,
    com.grepcepws.ws.ObjectFactory.class
})
public interface GrepCepPortType {


    /**
     * 
     * @param cep
     * @param token
     * @return
     *     returns com.grepcepws.entity.xsd.ObterCepResponse
     */
    @WebMethod(action = "urn:obterEnderecoCep")
    @WebResult(targetNamespace = "http://ws.grepcepws.com")
    @RequestWrapper(localName = "obterEnderecoCep", targetNamespace = "http://ws.grepcepws.com", className = "com.grepcepws.ws.ObterEnderecoCep")
    @ResponseWrapper(localName = "obterEnderecoCepResponse", targetNamespace = "http://ws.grepcepws.com", className = "com.grepcepws.ws.ObterEnderecoCepResponse")
    public ObterCepResponse obterEnderecoCep(
        @WebParam(name = "cep", targetNamespace = "http://ws.grepcepws.com")
        String cep,
        @WebParam(name = "token", targetNamespace = "http://ws.grepcepws.com")
        String token);

}
